name: Streamlit App CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Lint the code (optional)
      - name: Run Linter (flake8)
        run: pip install flake8 && flake8 --max-line-length=88 .

      # Run tests
      - name: Run Tests
        run: |
          pytest --maxfail=5 --disable-warnings

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install Streamlit
      - name: Install Streamlit
        run: |
          pip install streamlit
          
      # Deploy Streamlit app (to Streamlit Community Cloud or another service)
      - name: Deploy Streamlit App
        run: |
          streamlit run drupalfit_chatbot_app.py
